using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Collections;
using System.Collections.Generic;
using System;
using System.Linq;

namespace Eduverse.Infographic
{
    /// <summary>
    /// High-performance animation player for infographics.
    /// Plays animation sequences generated by the backend animation engine.
    /// </summary>
    public class InfographicAnimationPlayer : MonoBehaviour
    {
        [Header("References")]
        [SerializeField] private InfographicRenderer renderer;

        [Header("Playback Configuration")]
        [SerializeField] private bool autoPlay = true;
        [SerializeField] private bool enableInteractions = true;
        [SerializeField] private float playbackSpeed = 1.0f;

        [Header("Performance Optimization")]
        [SerializeField] private bool useCoroutinePooling = true;
        [SerializeField] private int maxConcurrentAnimations = 10;

        // Playback state
        private AnimationData currentAnimation;
        private bool isPlaying = false;
        private float currentTime = 0f;
        private List<Coroutine> activeCoroutines;

        // Element references (mapped to animated objects)
        private Dictionary<int, GameObject> elementObjects;

        // Events
        public event Action OnAnimationStart;
        public event Action OnAnimationComplete;
        public event Action<float> OnProgressUpdate; // 0.0 to 1.0

        private void Awake()
        {
            activeCoroutines = new List<Coroutine>();
            elementObjects = new Dictionary<int, GameObject>();
        }

        /// <summary>
        /// Load and optionally start playing an animation.
        /// </summary>
        public void LoadAnimation(string animationJson, bool play = true)
        {
            try
            {
                currentAnimation = JsonUtility.FromJson<AnimationData>(animationJson);

                Debug.Log($"[AnimationPlayer] Loaded animation: {currentAnimation.sequences.Length} sequences, {currentAnimation.total_duration}s");

                if (play && autoPlay)
                {
                    PlayAnimation();
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"[AnimationPlayer] Error loading animation: {e.Message}");
            }
        }

        /// <summary>
        /// Start playing the loaded animation.
        /// </summary>
        public void PlayAnimation()
        {
            if (currentAnimation == null)
            {
                Debug.LogWarning("[AnimationPlayer] No animation loaded");
                return;
            }

            if (isPlaying)
            {
                Debug.LogWarning("[AnimationPlayer] Animation already playing");
                return;
            }

            StartCoroutine(PlayAnimationCoroutine());
        }

        private IEnumerator PlayAnimationCoroutine()
        {
            isPlaying = true;
            currentTime = 0f;

            OnAnimationStart?.Invoke();

            Debug.Log($"[AnimationPlayer] Starting animation playback ({currentAnimation.total_duration}s)");

            // Map element IDs to GameObjects from renderer
            MapElementObjects();

            // Start all animation sequences
            List<Coroutine> sequenceCoroutines = new List<Coroutine>();

            foreach (var sequence in currentAnimation.sequences)
            {
                if (sequence.element_id < 0 || !elementObjects.ContainsKey(sequence.element_id))
                {
                    Debug.LogWarning($"[AnimationPlayer] Invalid element_id: {sequence.element_id}");
                    continue;
                }

                Coroutine coroutine = StartCoroutine(PlaySequenceCoroutine(sequence));
                sequenceCoroutines.Add(coroutine);
                activeCoroutines.Add(coroutine);

                // Limit concurrent animations for performance
                if (activeCoroutines.Count >= maxConcurrentAnimations)
                {
                    yield return new WaitForSeconds(0.05f);
                }
            }

            // Wait for animation to complete
            float startTime = Time.time;
            while (currentTime < currentAnimation.total_duration)
            {
                currentTime = (Time.time - startTime) * playbackSpeed;

                // Update progress
                float progress = Mathf.Clamp01(currentTime / currentAnimation.total_duration);
                OnProgressUpdate?.Invoke(progress);

                // Check for interaction points
                if (enableInteractions)
                {
                    yield return CheckInteractionPoints();
                }

                yield return null;
            }

            // Wait for all sequences to finish
            foreach (var coroutine in sequenceCoroutines)
            {
                if (coroutine != null)
                {
                    yield return coroutine;
                }
            }

            isPlaying = false;
            OnAnimationComplete?.Invoke();

            Debug.Log("[AnimationPlayer] Animation playback complete");
        }

        private IEnumerator PlaySequenceCoroutine(AnimationSequence sequence)
        {
            GameObject element = elementObjects[sequence.element_id];
            if (element == null)
            {
                Debug.LogWarning($"[AnimationPlayer] Element {sequence.element_id} is null");
                yield break;
            }

            // Wait for delay
            if (sequence.delay > 0)
            {
                yield return new WaitForSeconds(sequence.delay / playbackSpeed);
            }

            // Get components
            RectTransform rectTransform = element.GetComponent<RectTransform>();
            CanvasGroup canvasGroup = element.GetComponent<CanvasGroup>();
            if (canvasGroup == null)
            {
                canvasGroup = element.AddComponent<CanvasGroup>();
            }

            // Play animation based on type
            float startTime = Time.time;
            float duration = sequence.duration / playbackSpeed;

            while (Time.time - startTime < duration)
            {
                float t = (Time.time - startTime) / duration;

                // Find current keyframe
                var currentKeyframe = GetKeyframeAtTime(sequence.keyframes, t * sequence.duration);
                var nextKeyframe = GetNextKeyframe(sequence.keyframes, t * sequence.duration);

                if (currentKeyframe != null && nextKeyframe != null)
                {
                    float keyframeT = Mathf.InverseLerp(
                        currentKeyframe.time,
                        nextKeyframe.time,
                        t * sequence.duration
                    );

                    // Apply easing
                    keyframeT = ApplyEasing(keyframeT, currentKeyframe.easing);

                    // Interpolate and apply properties
                    ApplyKeyframeProperties(
                        element,
                        rectTransform,
                        canvasGroup,
                        currentKeyframe,
                        nextKeyframe,
                        keyframeT
                    );
                }

                yield return null;
            }

            // Ensure final state
            var finalKeyframe = sequence.keyframes.OrderByDescending(k => k.time).FirstOrDefault();
            if (finalKeyframe != null)
            {
                ApplyKeyframeProperties(
                    element,
                    rectTransform,
                    canvasGroup,
                    finalKeyframe,
                    finalKeyframe,
                    1.0f
                );
            }
        }

        private AnimationKeyframe GetKeyframeAtTime(AnimationKeyframe[] keyframes, float time)
        {
            AnimationKeyframe result = keyframes[0];
            foreach (var kf in keyframes)
            {
                if (kf.time <= time)
                {
                    result = kf;
                }
            }
            return result;
        }

        private AnimationKeyframe GetNextKeyframe(AnimationKeyframe[] keyframes, float time)
        {
            foreach (var kf in keyframes)
            {
                if (kf.time > time)
                {
                    return kf;
                }
            }
            return keyframes[keyframes.Length - 1];
        }

        private void ApplyKeyframeProperties(
            GameObject element,
            RectTransform rectTransform,
            CanvasGroup canvasGroup,
            AnimationKeyframe from,
            AnimationKeyframe to,
            float t
        )
        {
            // Opacity
            if (from.properties.ContainsKey("opacity") && to.properties.ContainsKey("opacity"))
            {
                float opacity = Mathf.Lerp(
                    (float)from.properties["opacity"],
                    (float)to.properties["opacity"],
                    t
                );
                canvasGroup.alpha = opacity;
            }

            // Scale
            if (from.properties.ContainsKey("scale") && to.properties.ContainsKey("scale"))
            {
                float scale = Mathf.Lerp(
                    (float)from.properties["scale"],
                    (float)to.properties["scale"],
                    t
                );
                rectTransform.localScale = Vector3.one * scale;
            }

            // Position X
            if (from.properties.ContainsKey("x") && to.properties.ContainsKey("x"))
            {
                float x = Mathf.Lerp(
                    (float)from.properties["x"],
                    (float)to.properties["x"],
                    t
                );
                Vector2 pos = rectTransform.anchoredPosition;
                pos.x = x * renderer.GetComponent<RectTransform>().rect.width;
                rectTransform.anchoredPosition = pos;
            }

            // Position Y
            if (from.properties.ContainsKey("y") && to.properties.ContainsKey("y"))
            {
                float y = Mathf.Lerp(
                    (float)from.properties["y"],
                    (float)to.properties["y"],
                    t
                );
                Vector2 pos = rectTransform.anchoredPosition;
                pos.y = y * renderer.GetComponent<RectTransform>().rect.height;
                rectTransform.anchoredPosition = pos;
            }

            // Typewriter effect (text reveal)
            if (from.properties.ContainsKey("characters_visible"))
            {
                int chars = Mathf.RoundToInt(Mathf.Lerp(
                    (float)from.properties["characters_visible"],
                    (float)to.properties["characters_visible"],
                    t
                ));

                TextMeshProUGUI text = element.GetComponentInChildren<TextMeshProUGUI>();
                if (text != null)
                {
                    text.maxVisibleCharacters = chars;
                }
            }
        }

        private float ApplyEasing(float t, string easingType)
        {
            return easingType switch
            {
                "linear" => t,
                "easeIn" => t * t,
                "easeOut" => 1 - (1 - t) * (1 - t),
                "easeInOut" => t < 0.5f ? 2 * t * t : 1 - Mathf.Pow(-2 * t + 2, 2) / 2,
                "bounce" => ApplyBounceEasing(t),
                "elastic" => ApplyElasticEasing(t),
                _ => t
            };
        }

        private float ApplyBounceEasing(float t)
        {
            const float n1 = 7.5625f;
            const float d1 = 2.75f;

            if (t < 1 / d1)
            {
                return n1 * t * t;
            }
            else if (t < 2 / d1)
            {
                return n1 * (t -= 1.5f / d1) * t + 0.75f;
            }
            else if (t < 2.5 / d1)
            {
                return n1 * (t -= 2.25f / d1) * t + 0.9375f;
            }
            else
            {
                return n1 * (t -= 2.625f / d1) * t + 0.984375f;
            }
        }

        private float ApplyElasticEasing(float t)
        {
            const float c4 = (2 * Mathf.PI) / 3;
            return t == 0 ? 0 : t == 1 ? 1 : Mathf.Pow(2, -10 * t) * Mathf.Sin((t * 10 - 0.75f) * c4) + 1;
        }

        private IEnumerator CheckInteractionPoints()
        {
            if (currentAnimation.interaction_points == null)
                yield break;

            foreach (var point in currentAnimation.interaction_points)
            {
                if (Mathf.Abs(currentTime - point.time) < 0.1f)
                {
                    // Pause and wait for user interaction
                    Debug.Log($"[AnimationPlayer] Interaction point: {point.message}");
                    isPlaying = false;

                    // TODO: Show interaction UI
                    yield return WaitForUserInteraction(point.message);

                    isPlaying = true;
                }
            }
        }

        private IEnumerator WaitForUserInteraction(string message)
        {
            // Wait for tap/click
            while (!Input.GetMouseButtonDown(0) && !Input.touchCount > 0)
            {
                yield return null;
            }

            Debug.Log("[AnimationPlayer] User interaction received");
        }

        private void MapElementObjects()
        {
            elementObjects.Clear();

            InfographicData infographic = renderer.GetCurrentInfographic();
            if (infographic == null)
            {
                Debug.LogError("[AnimationPlayer] No infographic loaded in renderer");
                return;
            }

            // Find all child objects in renderer
            Transform container = renderer.transform;
            List<GameObject> children = new List<GameObject>();

            for (int i = 0; i < container.childCount; i++)
            {
                children.Add(container.GetChild(i).gameObject);
            }

            // Map by index
            for (int i = 0; i < children.Count && i < infographic.elements.Length; i++)
            {
                elementObjects[i] = children[i];
            }

            Debug.Log($"[AnimationPlayer] Mapped {elementObjects.Count} element objects");
        }

        public void PauseAnimation()
        {
            isPlaying = false;
            Time.timeScale = 0f;
        }

        public void ResumeAnimation()
        {
            isPlaying = true;
            Time.timeScale = 1f;
        }

        public void StopAnimation()
        {
            isPlaying = false;

            // Stop all coroutines
            foreach (var coroutine in activeCoroutines)
            {
                if (coroutine != null)
                {
                    StopCoroutine(coroutine);
                }
            }

            activeCoroutines.Clear();
            currentTime = 0f;
        }

        public float GetProgress()
        {
            if (currentAnimation == null || currentAnimation.total_duration == 0)
                return 0f;

            return Mathf.Clamp01(currentTime / currentAnimation.total_duration);
        }
    }

    // Animation data structures matching backend JSON
    [Serializable]
    public class AnimationData
    {
        public string infographic_id;
        public float total_duration;
        public AnimationSequence[] sequences;
        public InteractionPoint[] interaction_points;
    }

    [Serializable]
    public class AnimationSequence
    {
        public int element_id;
        public string type;
        public AnimationKeyframe[] keyframes;
        public float duration;
        public float delay;
        public bool loop;
    }

    [Serializable]
    public class AnimationKeyframe
    {
        public float time;
        public Dictionary<string, object> properties;
        public string easing;
    }

    [Serializable]
    public class InteractionPoint
    {
        public float time;
        public string type;
        public string message;
    }
}
