using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Collections;
using System.Collections.Generic;
using System;

namespace Eduverse.Infographic
{
    /// <summary>
    /// High-performance infographic renderer with animation support.
    /// Renders infographics generated by the backend pipeline.
    /// </summary>
    public class InfographicRenderer : MonoBehaviour
    {
        [Header("Rendering Configuration")]
        [SerializeField] private Canvas canvas;
        [SerializeField] private RectTransform container;
        [SerializeField] private float canvasWidth = 1920f;
        [SerializeField] private float canvasHeight = 1080f;

        [Header("Element Prefabs")]
        [SerializeField] private GameObject textElementPrefab;
        [SerializeField] private GameObject iconElementPrefab;
        [SerializeField] private GameObject chartElementPrefab;
        [SerializeField] private GameObject diagramElementPrefab;
        [SerializeField] private GameObject imageElementPrefab;

        [Header("Performance")]
        [SerializeField] private bool enableObjectPooling = true;
        [SerializeField] private int poolSize = 20;

        // Object pools for performance
        private Dictionary<string, Queue<GameObject>> elementPools;
        private List<GameObject> activeElements;

        // Current infographic data
        private InfographicData currentInfographic;

        private void Awake()
        {
            if (enableObjectPooling)
            {
                InitializeObjectPools();
            }

            activeElements = new List<GameObject>();
        }

        private void InitializeObjectPools()
        {
            elementPools = new Dictionary<string, Queue<GameObject>>
            {
                { "text", new Queue<GameObject>() },
                { "icon", new Queue<GameObject>() },
                { "chart", new Queue<GameObject>() },
                { "diagram", new Queue<GameObject>() },
                { "image", new Queue<GameObject>() }
            };

            // Pre-create pooled objects
            foreach (var poolType in elementPools.Keys)
            {
                for (int i = 0; i < poolSize / elementPools.Count; i++)
                {
                    GameObject prefab = GetPrefabForType(poolType);
                    if (prefab != null)
                    {
                        GameObject obj = Instantiate(prefab, container);
                        obj.SetActive(false);
                        elementPools[poolType].Enqueue(obj);
                    }
                }
            }

            Debug.Log($"[InfographicRenderer] Object pools initialized: {poolSize} objects");
        }

        private GameObject GetPrefabForType(string elementType)
        {
            return elementType switch
            {
                "text" => textElementPrefab,
                "icon" => iconElementPrefab,
                "chart" => chartElementPrefab,
                "diagram" => diagramElementPrefab,
                "image" => imageElementPrefab,
                _ => textElementPrefab
            };
        }

        private GameObject GetPooledObject(string elementType)
        {
            if (!enableObjectPooling)
            {
                GameObject prefab = GetPrefabForType(elementType);
                return prefab != null ? Instantiate(prefab, container) : null;
            }

            if (elementPools.ContainsKey(elementType) && elementPools[elementType].Count > 0)
            {
                GameObject obj = elementPools[elementType].Dequeue();
                obj.SetActive(true);
                return obj;
            }

            // Pool exhausted, create new object
            GameObject newObj = Instantiate(GetPrefabForType(elementType), container);
            return newObj;
        }

        private void ReturnToPool(GameObject obj, string elementType)
        {
            if (!enableObjectPooling)
            {
                Destroy(obj);
                return;
            }

            obj.SetActive(false);
            if (elementPools.ContainsKey(elementType))
            {
                elementPools[elementType].Enqueue(obj);
            }
        }

        /// <summary>
        /// Render infographic from JSON data.
        /// </summary>
        public void RenderInfographic(string infographicJson)
        {
            try
            {
                // Parse JSON
                currentInfographic = JsonUtility.FromJson<InfographicData>(infographicJson);

                // Clear previous infographic
                ClearInfographic();

                // Set background
                if (container.TryGetComponent<Image>(out Image bg))
                {
                    bg.color = ParseColor(currentInfographic.background_color);
                }

                // Render each element
                for (int i = 0; i < currentInfographic.elements.Length; i++)
                {
                    RenderElement(currentInfographic.elements[i], i);
                }

                Debug.Log($"[InfographicRenderer] Rendered '{currentInfographic.title}' with {currentInfographic.elements.Length} elements");
            }
            catch (Exception e)
            {
                Debug.LogError($"[InfographicRenderer] Error rendering infographic: {e.Message}");
            }
        }

        private void RenderElement(InfographicElement element, int index)
        {
            GameObject elementObj = GetPooledObject(element.type);
            if (elementObj == null)
            {
                Debug.LogWarning($"No prefab for element type: {element.type}");
                return;
            }

            RectTransform rectTransform = elementObj.GetComponent<RectTransform>();
            if (rectTransform == null)
            {
                Debug.LogError($"Element missing RectTransform: {element.type}");
                return;
            }

            // Position (normalized 0-1 to canvas space)
            float x = element.position.x * canvasWidth;
            float y = element.position.y * canvasHeight;
            float width = element.position.width * canvasWidth;
            float height = element.position.height * canvasHeight;

            rectTransform.anchorMin = new Vector2(0, 0);
            rectTransform.anchorMax = new Vector2(0, 0);
            rectTransform.pivot = new Vector2(0.5f, 0.5f);
            rectTransform.anchoredPosition = new Vector2(x, y);
            rectTransform.sizeDelta = new Vector2(width, height);

            // Set content based on type
            switch (element.type)
            {
                case "text":
                    RenderTextElement(elementObj, element);
                    break;
                case "icon":
                    RenderIconElement(elementObj, element);
                    break;
                case "chart":
                    RenderChartElement(elementObj, element);
                    break;
                case "diagram":
                    RenderDiagramElement(elementObj, element);
                    break;
                case "image":
                    RenderImageElement(elementObj, element);
                    break;
            }

            activeElements.Add(elementObj);
        }

        private void RenderTextElement(GameObject obj, InfographicElement element)
        {
            TextMeshProUGUI text = obj.GetComponentInChildren<TextMeshProUGUI>();
            if (text != null)
            {
                text.text = element.content;

                // Apply style
                if (element.style != null)
                {
                    if (element.style.ContainsKey("fontSize"))
                    {
                        text.fontSize = element.style["fontSize"] == "large" ? 48 :
                                       element.style["fontSize"] == "medium" ? 32 : 24;
                    }

                    if (element.style.ContainsKey("color"))
                    {
                        text.color = ParseColor(element.style["color"] as string);
                    }
                }
            }
        }

        private void RenderIconElement(GameObject obj, InfographicElement element)
        {
            Image icon = obj.GetComponent<Image>();
            if (icon != null && element.style != null && element.style.ContainsKey("iconName"))
            {
                string iconName = element.style["iconName"] as string;
                // Load icon from Resources (simplified)
                Sprite iconSprite = Resources.Load<Sprite>($"Icons/{iconName}");
                if (iconSprite != null)
                {
                    icon.sprite = iconSprite;
                }
            }

            // Set color if specified
            if (element.style != null && element.style.ContainsKey("color"))
            {
                if (icon != null)
                {
                    icon.color = ParseColor(element.style["color"] as string);
                }
            }
        }

        private void RenderChartElement(GameObject obj, InfographicElement element)
        {
            // TODO: Implement chart rendering
            // For now, use simple bars
            Debug.Log($"[InfographicRenderer] Rendering chart: {element.content}");

            // Charts would use Unity UI Toolkit or custom mesh generation
            // Simplified placeholder
            TextMeshProUGUI label = obj.GetComponentInChildren<TextMeshProUGUI>();
            if (label != null)
            {
                label.text = element.content;
            }
        }

        private void RenderDiagramElement(GameObject obj, InfographicElement element)
        {
            // TODO: Implement diagram rendering
            Debug.Log($"[InfographicRenderer] Rendering diagram: {element.content}");

            TextMeshProUGUI label = obj.GetComponentInChildren<TextMeshProUGUI>();
            if (label != null)
            {
                label.text = element.content;
            }
        }

        private void RenderImageElement(GameObject obj, InfographicElement element)
        {
            // TODO: Load and display image
            Debug.Log($"[InfographicRenderer] Rendering image: {element.content}");

            Image img = obj.GetComponent<Image>();
            if (img != null)
            {
                // Load from URL or Resources
                // Placeholder for now
            }
        }

        private Color ParseColor(string hexColor)
        {
            if (string.IsNullOrEmpty(hexColor))
                return Color.white;

            if (ColorUtility.TryParseHtmlString(hexColor, out Color color))
            {
                return color;
            }

            return Color.white;
        }

        /// <summary>
        /// Clear all rendered elements.
        /// </summary>
        public void ClearInfographic()
        {
            foreach (GameObject obj in activeElements)
            {
                if (obj != null)
                {
                    string elementType = DetermineElementType(obj);
                    ReturnToPool(obj, elementType);
                }
            }

            activeElements.Clear();
            Debug.Log("[InfographicRenderer] Infographic cleared");
        }

        private string DetermineElementType(GameObject obj)
        {
            // Simple type detection based on component
            if (obj.GetComponentInChildren<TextMeshProUGUI>() != null)
                return "text";
            if (obj.GetComponent<Image>() != null)
                return "icon";

            return "text"; // Default
        }

        public InfographicData GetCurrentInfographic()
        {
            return currentInfographic;
        }
    }

    // Data structures matching backend JSON
    [Serializable]
    public class InfographicData
    {
        public string title;
        public string subtitle;
        public InfographicElement[] elements;
        public string background_color;
        public string theme_color;
        public string style;
    }

    [Serializable]
    public class InfographicElement
    {
        public string type;
        public string content;
        public ElementPosition position;
        public Dictionary<string, object> style;
        public Dictionary<string, object> data;
    }

    [Serializable]
    public class ElementPosition
    {
        public float x;
        public float y;
        public float width;
        public float height;
    }
}
